code4sac/neighborhood-connect

- src/components/Post.js
- src/components/PriorityDetails.js
This will add the filtering for AJAX requests for Past and Upcoming events
> add ajax requests for filtering

- src/components/NewPriorityForm.js
- src/components/PostPage.js
also added method to update state in form.
> create page for individual post

- src/App.js
- src/components/NewEventForm.js
- src/components/NewPriorityForm.js
> change form names

- package.json
- src/components/Layout.test.js
- src/components/Post.test.js
- src/components/PrioritiesPage.test.js
- src/components/PriorityCard.js
- src/components/PriorityCard.test.js
- src/components/PriorityDetails.test.js
run 'yarn coverage' to see unit test coverage
> Add unit tests and coverage option

- src/App.js
- src/components/Post.js
- src/components/PriorityDetails.js
- src/components/seed.js
Add mockdata and toggle for past and upcoming
> Development f mockdata

- src/App.js
- src/components/NeighborhoodSelector.js
- src/components/PrioritiesPage.js
- src/components/PriorityCard.js
Add neighborhood selector component. Add app-level state for neighborhood selection.
> Neighborhood selector

- src/components/PrioritiesOrderPage.js
- src/components/PriorityCard.js
moved the buttons for reordering into the PriorityCard component (with some basic style)
> added buttons to PriorityCard when at edit page

- src/components/FilteredOrgList.js
- src/components/NeighborhoodSelector.js
- src/components/PriorityCard.js
- src/components/PriorityDetails.js
- src/sass/abstract/_variables.scss
- src/sass/base/_typography.scss
- src/sass/base/_utilities.scss
- src/sass/components/_orglist.scss
- src/sass/components/_searchform.scss
- src/sass/layout/_prioritydetails.scss
- src/sass/main.scss
This will add initial styles to the neighborhood selector page.
> add initial styling to NeighborhoodSelector.js

- src/components/CreateAccount.js
- src/components/PrioritiesPage.js
Created fetch request (backend not ready yet for queries) and renamed state keys to match db Users fields.
> refactor CreateAccount for POST request

- src/components/NeighborhoodSelector.js
in useEffects we are loading the org list page.  Clear out the search string so that all orgs show.
> Clear search string when the org list page is loaded

- src/components/ActionsPage.js
- src/components/ActionsPage.test.js
> Clear search entering org list

- src/components/Header.js
- src/components/LocationHolder.js
- src/components/NeighborhoodSelector.js
- src/sass/components/_button.scss
- src/sass/components/_locationholder.scss
- src/sass/components/_seperator.scss
There were some components that were sitting the page, but not being rendered properly or didnt have styles to correctly display them. This fixes:
- showing the currently selected neighborhood on the LocationHolder.js component
- conditionally render header's button options
> found invisible components, and fixed their rendering

- src/App.js
- src/components/ActionsPage.js
- src/components/NewActionForm.js
- src/components/PrioritiesPage.js
Fixes actions display (it was showing actions based on their id, not the priority id) and implement the post request for new action.
> Post actions

- src/components/PrioritiesOrderPage.js
- src/components/PriorityCard.js
Priority cards link to actions when on editPriorities page.
> Priority card link

- src/App.js
- src/components/NeighborhoodSelector.js
Loads neighborhood last used from localStorage.
> read neighborhood from localstorage

- src/components/NewActionForm.js
- src/components/NewPriorityForm.js
Adds a required to form submitting
> add required attribute to forms

- src/components/LocationHolder.js
- src/components/NewActionForm.js
- src/components/NewPriorityForm.js
- src/sass/components/_linktopage.scss
- src/sass/components/_locationholder.scss
- src/sass/components/_searchform.scss
- src/sass/layout/_formpages.scss
- src/sass/layout/_prioritiespage.scss
- src/sass/layout/_prioritydetails.scss
This will add media queries for 1280px resolutions and higher, so component views don't stretch to 100% of screen.
Also minor changes to placeholders for inputs.
> create desktop responsiveness for 1280+ viewport

- src/App.js
- src/components/PrioritiesOrderPage.js
- src/components/PrioritiesPage.js
Hey guys, I went ahead and made a few changes to prioritiesOrder page. I fetchPriorities to make it it's own method and then refactored promotePriority, demotePriority to match. Sorry if I messed up the linter stuff.
> Promote demote priority

- src/components/NewPriorityForm.js
Somehow this method is still here.
> remove unused(old) method

- src/components/Action.js
- src/components/NewActionForm.js
- src/sass/components/_action.scss
Fixes the text from spilling over into another section of the Action component. Also added an error catch to the fetch block for Action POST.
> Fix cards responsiveness

- src/App.js
- src/components/FilteredOrgList.js
- src/components/NeighborhoodSelector.js
- src/components/PrioritiesPage.js
- src/components/seed.js
backend PR is merged, so merging this is OK now.
> Multiple search types

- src/sass/components/_locationholder.scss
- src/sass/components/_searchform.scss
- src/sass/layout/_formpages.scss
- src/sass/layout/_prioritiespage.scss
- src/sass/layout/_prioritydetails.scss
Quick adjustment of the width for multiple components.
> fixes viewports at 1280

- .eslintrc.js
- package-lock.json
- package.json
This should set up the AirBnB aslant style.
> WIP Add basic AirBnB config from elint --init

- .eslintrc.js
- src/components/PrioritiesPage.js
Fixes #89 
Also some lint cleanup
> Update lint, fix priorities page warning.  fixes issue 89

- README.md
In response to issue #44, a simple first pass.
> improve README resolve issue #44

- src/components/NeighborhoodSelector.js
- src/components/seed.js
> Fetch priority types from API
